In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('E:\\Trainings\\Complete Data Science Bootcamp - Udemy\\sklearn\\Simple Linear Regression\\Latest\\1.01.Simple-linear-regression.csv')

In [3]:
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
data.describe()

SAT        GPA
count    84.000000  84.000000
mean   1845.273810   3.330238
std     104.530661   0.271617
min    1634.000000   2.400000
25%    1772.000000   3.190000
50%    1846.000000   3.380000
75%    1934.000000   3.502500
max    2050.000000   3.810000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 2 columns):
SAT    84 non-null int64
GPA    84 non-null float64
dtypes: float64(1), int64(1)
memory usage: 1.4 KB


In [6]:
x = data['SAT']
y = data['GPA']

In [7]:
x.shape

(84,)

In [8]:
y.shape

(84,)

In [9]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [10]:
reg = LinearRegression()

In [11]:
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
reg.score(x_matrix,y)

0.40600391479679765

In [13]:
reg.coef_

array([0.00165569])

In [14]:
reg.intercept_

0.275040299660279

In [15]:
reg.predict([[1740]])

array([3.15593751])

In [23]:
new_data = pd.DataFrame(data=[1740,1760],columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [24]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [25]:
new_data['Predicted_GPA'] = reg.predict(new_data)
new_data

SAT  Predicted_GPA
0  1740       3.155938
1  1760       3.189051