In [1]:
import numpy as np
import pandas as pd

In [2]:
df_preprocessed = pd.read_csv("E:\\Trainings\\Complete Data Science Bootcamp - Udemy\\End to End Case Study - Absenteeism\\Absenteeism_preprocessed.csv")

In [3]:
df_preprocessed.head(5)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
df_preprocessed.shape

(700, 15)

In [5]:
df_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
Reason_1                     700 non-null int64
Reason_2                     700 non-null int64
Reason_3                     700 non-null int64
Reason_4                     700 non-null int64
Month Value                  700 non-null int64
Day of the Week              700 non-null int64
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(14)
memory usage: 82.2 KB


In [6]:
df_preprocessed.describe()

Reason_1    Reason_2    Reason_3    Reason_4  Month Value  \
count  700.000000  700.000000  700.000000  700.000000    700.00000   
mean     0.250000    0.008571    0.135714    0.551429      6.36000   
std      0.433322    0.092250    0.342730    0.497704      3.50501   
min      0.000000    0.000000    0.000000    0.000000      1.00000   
25%      0.000000    0.000000    0.000000    0.000000      3.00000   
50%      0.000000    0.000000    0.000000    1.000000      6.00000   
75%      0.250000    0.000000    0.000000    1.000000     10.00000   
max      1.000000    1.000000    1.000000    1.000000     12.00000   

       Day of the Week  Transportation Expense  Distance to Work         Age  \
count       700.000000              700.000000        700.000000  700.000000   
mean          2.011429              222.347143         29.892857   36.417143   
std           1.480396               66.312960         14.804446    6.379083   
min           0.000000              118.000000          5.000000   27.000000   
25%           1.000000              179.000000         16.000000   31.000000   
50%           2.000000              225.000000         26.000000   37.000000   
75%           3.000000              260.000000         50.000000   40.000000   
max           6.000000              388.000000         52.000000   58.000000   

       Daily Work Load Average  Body Mass Index   Education    Children  \
count               700.000000       700.000000  700.000000  700.000000   
mean                271.801774        26.737143    0.167143    1.021429   
std                  40.021804         4.254701    0.373370    1.112215   
min                 205.917000        19.000000    0.000000    0.000000   
25%                 241.476000        24.000000    0.000000    0.000000   
50%                 264.249000        25.000000    0.000000    1.000000   
75%                 294.217000        31.000000    0.000000    2.000000   
max                 378.884000        38.000000    1.000000    4.000000   

             Pets  Absenteeism Time in Hours  
count  700.000000                 700.000000  
mean     0.687143                   6.761429  
std      1.166095                  12.670082  
min      0.000000                   0.000000  
25%      0.000000                   2.000000  
50%      0.000000                   3.000000  
75%      1.000000                   8.000000  
max      8.000000                 120.000000

### Create the Targets

We will create 2 classes in our data to reflect absenteeism:<br>
a. Moderately Absent (<=3 Hours) - assing 0<br>
b. Excessively Absent (> 3 Hours) - assign 1<br>

This can be done based on median on "absenteeism time in hours column"

In [7]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
targets = np.where(df_preprocessed['Absenteeism Time in Hours'] >
                   df_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
df_preprocessed['Excessive Absenteeism'] = targets

In [11]:
df_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1            7                4   
6         0         0         1         0            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            7                0   
9         0         0         1         0            7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   
5               31          0         0     0                          2   
6               27          0         1     4                          8   
7               23          0         4     0                          4   
8               25          0         2     0                         40   
9               29          1         1     1                          8   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  
5                      0  
6                      1  
7                      1  
8                      1  
9                      1

In [12]:
targets.sum() / targets.shape[0]

0.45571428571428574

Nearly 46 % values are 1, whereas remaining 54% are 0

In [13]:
data_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Distance to Work',
                                          'Daily Work Load Average'], axis=1)

In [14]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [15]:
# Check if the 2 variables are pointing to the same memory location
data_with_targets is df_preprocessed

False

#### Select Inputs for the Regression

In [16]:
data_with_targets.shape

(700, 12)

In [17]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [18]:
# Same as above, but another way to slice
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [19]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [20]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

#### Standardize the data

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
absenteeism_scaler = StandardScaler()

In [23]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [24]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [25]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [26]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [27]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [28]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [29]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [30]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [31]:
scaled_inputs.shape

(700, 11)

#### Train and Test Split

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, test_size=0.2, shuffle=True, random_state=365)

In [34]:
x_train.shape, y_train.shape

((560, 11), (560,))

In [35]:
x_test.shape, y_test.shape

((140, 11), (140,))

#### Logistic Regression with sklearn

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [37]:
reg = LogisticRegression()

In [38]:
reg.fit(x_train, y_train)

C:\Users\SONY\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
reg.score(x_train, y_train)

0.7839285714285714

### Manually validating the model beyond just score method

In [40]:
model_outputs = reg.predict(x_train)

In [41]:
model_outputs

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,

In [42]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [43]:
## Compares 2 outputs and returns True if match found
model_outputs == y_train

array([ True,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False, False,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [44]:
# Check total number of True entries
np.sum(model_outputs == y_train)

439

In [45]:
model_outputs.shape[0]

560

In [46]:
# Accuracy
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7839285714285714

### Find the intercept and the coefficients

In [47]:
## This is mainly to use model outside of Python like Tableau, etc. we will create a function which can be used

In [48]:
reg.intercept_

array([-1.34773292])

In [49]:
reg.coef_

array([[ 2.48606257,  1.26893362,  3.14356813,  0.45315672,  0.19248052,
         0.41357993, -0.26031811,  0.29794864, -0.30089218,  0.41271115,
        -0.44965245]])

In [50]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [51]:
feature_name = unscaled_inputs.columns.values

In [52]:
summary_table = pd.DataFrame(data=feature_name, columns=['Feature_name'])
summary_table

Feature_name
0                 Reason_1
1                 Reason_2
2                 Reason_3
3                 Reason_4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                    Pets

In [53]:
## We have to transpose this because by default ndarrays are columns and we need it in rows
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [54]:
summary_table

Feature_name  Coefficient
0                 Reason_1     2.486063
1                 Reason_2     1.268934
2                 Reason_3     3.143568
3                 Reason_4     0.453157
4              Month Value     0.192481
5   Transportation Expense     0.413580
6                      Age    -0.260318
7          Body Mass Index     0.297949
8                Education    -0.300892
9                 Children     0.412711
10                    Pets    -0.449652

In [55]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature_name  Coefficient
0                Intercept    -1.347733
1                 Reason_1     2.486063
2                 Reason_2     1.268934
3                 Reason_3     3.143568
4                 Reason_4     0.453157
5              Month Value     0.192481
6   Transportation Expense     0.413580
7                      Age    -0.260318
8          Body Mass Index     0.297949
9                Education    -0.300892
10                Children     0.412711
11                    Pets    -0.449652

#### Interpreting coefficients

In [56]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature_name  Coefficient  Odds_ratio
0                Intercept    -1.347733    0.259829
1                 Reason_1     2.486063   12.013879
2                 Reason_2     1.268934    3.557057
3                 Reason_3     3.143568   23.186452
4                 Reason_4     0.453157    1.573271
5              Month Value     0.192481    1.212253
6   Transportation Expense     0.413580    1.512222
7                      Age    -0.260318    0.770806
8          Body Mass Index     0.297949    1.347093
9                Education    -0.300892    0.740158
10                Children     0.412711    1.510909
11                    Pets    -0.449652    0.637850

In [57]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature_name  Coefficient  Odds_ratio
3                 Reason_3     3.143568   23.186452
1                 Reason_1     2.486063   12.013879
2                 Reason_2     1.268934    3.557057
4                 Reason_4     0.453157    1.573271
6   Transportation Expense     0.413580    1.512222
10                Children     0.412711    1.510909
8          Body Mass Index     0.297949    1.347093
5              Month Value     0.192481    1.212253
7                      Age    -0.260318    0.770806
9                Education    -0.300892    0.740158
11                    Pets    -0.449652    0.637850
0                Intercept    -1.347733    0.259829

#### Testing the model

In [58]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.8

In [59]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.6011115 , 0.3988885 ],
       [0.66482565, 0.33517435],
       [0.07023509, 0.92976491],
       [0.16266801, 0.83733199],
       [0.15648731, 0.84351269],
       [0.30990202, 0.69009798],
       [0.19386829, 0.80613171],
       [0.54383685, 0.45616315],
       [0.14526885, 0.85473115],
       [0.28638518, 0.71361482],
       [0.87380539, 0.12619461],
       [0.87974182, 0.12025818],
       [0.77673294, 0.22326706],
       [0.06673007, 0.93326993],
       [0.26255754, 0.73744246],
       [0.69387641, 0.30612359],
       [0.57448855, 0.42551145],
       [0.57448855, 0.42551145],
       [0.1522215 , 0.8477785 ],
       [0.78325988, 0.21674012],
       [0.86443948, 0.13556052],
       [0.7109659 , 0.2890341 ],
       [0.35163565, 0.64836435],
       [0.56100289, 0.43899711],
       [0.88232622, 0.11767378],
       [0.42361834, 0.57638166],
       [0.8687366 , 0.1312634 ],
       [0.80553839, 0.19446161],
       [0.33115025, 0.66884975],
       [0.69827392, 0.30172608],
       [0.

In [60]:
predicted_proba.shape

(140, 2)

In [61]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.3988885 , 0.33517435, 0.92976491, 0.83733199, 0.84351269,
       0.69009798, 0.80613171, 0.45616315, 0.85473115, 0.71361482,
       0.12619461, 0.12025818, 0.22326706, 0.93326993, 0.73744246,
       0.30612359, 0.42551145, 0.42551145, 0.8477785 , 0.21674012,
       0.13556052, 0.2890341 , 0.64836435, 0.43899711, 0.11767378,
       0.57638166, 0.1312634 , 0.19446161, 0.66884975, 0.30172608,
       0.68701006, 0.17431312, 0.66655013, 0.76774603, 0.34011252,
       0.78544618, 0.59677293, 0.92976491, 0.62796332, 0.62460519,
       0.87873799, 0.64739148, 0.18538691, 0.18538691, 0.19383001,
       0.92654931, 0.55537266, 0.26497273, 0.70009702, 0.31213225,
       0.21674012, 0.26344859, 0.76308181, 0.18320477, 0.46955099,
       0.73554018, 0.32304152, 0.23597849, 0.21674012, 0.3525526 ,
       0.30045656, 0.36254932, 0.79165013, 0.50456492, 0.28692403,
       0.66655013, 0.82785647, 0.18320477, 0.22793497, 0.31213225,
       0.67205691, 0.15842236, 0.12477808, 0.36692872, 0.28277

#### Save the model

In [62]:
# import the relevant module
import pickle

In [63]:
# pickle the model file
with open('E:\\Trainings\\Complete Data Science Bootcamp - Udemy\\End to End Case Study - Absenteeism\\model', 'wb') as file:
    pickle.dump(reg, file)

In [64]:
# pickle the scaler file
with open('E:\\Trainings\\Complete Data Science Bootcamp - Udemy\\End to End Case Study - Absenteeism\\scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)