In [1]:
import numpy as np

In [2]:
s = 5

In [3]:
v = np.array([3,4,5])

In [4]:
m = np.array([[3,5,5],[6,7,8]])

In [5]:
s

5

In [6]:
v

array([3, 4, 5])

In [7]:
m

array([[3, 5, 5],
       [6, 7, 8]])

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)

In [12]:
s_array

array(5)

In [13]:
type(s_array)

numpy.ndarray

In [15]:
v.shape

(3,)

In [16]:
m.shape

(2, 3)

In [17]:
s_array.shape

()

In [18]:
v.reshape(1,3)

array([[3, 4, 5]])

In [19]:
v.reshape(3,1)

array([[3],
       [4],
       [5]])

In [20]:
m+s

array([[ 8, 10, 10],
       [11, 12, 13]])

In [21]:
m+s_array

array([[ 8, 10, 10],
       [11, 12, 13]])

In [22]:
v

array([3, 4, 5])

In [23]:
s

5

In [24]:
v+s

array([ 8,  9, 10])

In [25]:
v+s_array

array([ 8,  9, 10])

In [27]:
m

array([[3, 5, 5],
       [6, 7, 8]])

In [28]:
v

array([3, 4, 5])

In [29]:
m+v

array([[ 6,  9, 10],
       [ 9, 11, 13]])